name: Main CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  test-and-coverage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up fake GCS server
        run: |
          docker run -d \
          -p 4443:4443 \
          --mount type=bind,\
          src=${{ github.workspace }}/tests/test_files,\
          dst=/data/bucket/tests/test_files \
          fsouza/fake-gcs-server:1.47.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]

      - name: Run tests
        run: |
          python -m coverage run -m unittest discover tests
          python -m coverage lcov

      - name: Python ${{ matrix.python-version }} Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: python-${{ matrix.python-version }}-run
          parallel: true


  finish:

    needs: test-and-coverage
    runs-on: ubuntu-latest

    steps:
    - name: Update Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true